version: '3.3'

volumes:
  db_value:
  static_value:
  media_value:

services:

  db:
    image: postgres:13
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: qtafy/foodgram_backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db
  frontend:
    image: qtafy/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: qtafy/foodgram_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend